## Lesson 8

In [3]:
import numpy as np
linear_range = np.arange(20)
linear_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
linear_range < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [5]:
linear_range > 10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [7]:
linear_range[linear_range < 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr = np.array([1, 2, 3, 4, 5])
bool_arr = np.array ([True, False, True, False, False])
arr[bool_arr]

array([1, 3])

In [12]:
linear_range[(linear_range < 10) * (linear_range % 2 == 0)] 

array([0, 2, 4, 6, 8])

In [13]:
first_shape = np.ones((3, 5))
first_shape

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
second_shape = np.ones((2, 7)) * 3
second_shape

array([[3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.]])

In [20]:
#third_shape = np.ones(5) *  2
third_shape = np.array([1, 2, 3, 4, 5])
third_shape

array([1, 2, 3, 4, 5])

In [17]:
# first_shape + second_shape - форми масиву різні, numpy не розуміє як об'єднати

ValueError: operands could not be broadcast together with shapes (3,5) (2,7) 

In [21]:
first_shape + third_shape

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [22]:
four_shape = np.ones(3) * 2
four_shape

array([2., 2., 2.])

In [24]:
# four_shape + first_shape

ValueError: operands could not be broadcast together with shapes (3,) (3,5) 

Генерація випадкових чисел

In [26]:
np.random.random(size=(5, 5))

array([[0.28095451, 0.61751444, 0.24831711, 0.59705946, 0.9256055 ],
       [0.55558949, 0.9039048 , 0.28653497, 0.15643637, 0.53000876],
       [0.02572315, 0.28561297, 0.87836132, 0.34540209, 0.34691177],
       [0.16317543, 0.0017911 , 0.49162925, 0.10806368, 0.88180191],
       [0.38019662, 0.27970502, 0.04765123, 0.50455827, 0.95575441]])

In [27]:
np.random.random(size=10) * 90 + 10

array([97.33376342, 87.37536254, 25.2238391 , 60.88098366, 39.46909563,
       60.95186763, 11.3017909 , 68.69315493, 49.471012  , 63.92084731])

In [28]:
np.random.random? #підказка по функції

In [29]:
np.array?? # підказка, яка може показати також і код

In [30]:
np.arr*? # підказка які ще є методи, змінні, атрибути

In [31]:
np.random.*dom? # підказка

In [32]:
np.random.randint(5, 10, size=(5, 5))

array([[6, 5, 7, 6, 6],
       [7, 6, 5, 5, 6],
       [5, 9, 7, 7, 5],
       [9, 9, 8, 9, 5],
       [7, 8, 8, 6, 9]])

In [33]:
np.random.randint(5, 10, size=(5, 5)) > 5

array([[ True,  True,  True, False,  True],
       [ True,  True, False,  True, False],
       [False,  True,  True, False,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

Методи armin, argmax, argsort

In [60]:
a = np.arange(27)*5
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130])

In [61]:
np.argmin(a)

0

In [62]:
np.argmax(a)

26

In [63]:
np.argsort(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26], dtype=int64)

In [69]:
randin_arr = np.random.randint(10, 100, size=(5, 5))
randin_arr

array([[59, 83, 88, 74, 98],
       [27, 46, 35, 59, 87],
       [68, 88, 88, 28, 16],
       [22, 89, 24, 24, 76],
       [46, 38, 97, 32, 86]])

In [74]:
randin_arr.argmin(axis=0)

array([3, 4, 3, 3, 2], dtype=int64)

In [75]:
randin_arr.argmin(axis=1)

array([0, 0, 4, 0, 3], dtype=int64)

In [76]:
randin_arr.argmax(axis=0)

array([2, 3, 4, 0, 0], dtype=int64)

In [77]:
randin_arr.argmax(axis=1)

array([4, 4, 1, 1, 2], dtype=int64)

In [80]:
randin_arr.argsort(axis = 0)

array([[3, 4, 3, 3, 2],
       [1, 1, 1, 2, 3],
       [4, 0, 0, 4, 4],
       [0, 2, 2, 1, 1],
       [2, 3, 4, 0, 0]], dtype=int64)

In [81]:
randin_arr.argsort(axis = 1)

array([[0, 3, 1, 2, 4],
       [0, 2, 1, 3, 4],
       [4, 3, 0, 1, 2],
       [0, 2, 3, 4, 1],
       [3, 1, 0, 4, 2]], dtype=int64)

In [82]:
randin_arr.argsort()

array([[0, 3, 1, 2, 4],
       [0, 2, 1, 3, 4],
       [4, 3, 0, 1, 2],
       [0, 2, 3, 4, 1],
       [3, 1, 0, 4, 2]], dtype=int64)

Percentile (Процентиль)

In [83]:
randint_arr = np.array([*np.random.randint(0, 10, size=20), 1000])
randint_arr

array([   5,    1,    5,    6,    6,    9,    3,    7,    8,    1,    5,
          3,    8,    6,    7,    8,    2,    4,    3,    9, 1000])

In [85]:
np.percentile(randint_arr, 10)

2.0

In [86]:
np.percentile(randint_arr, 75)

8.0

In [87]:
np.percentile(randint_arr, 50)

6.0

In [89]:
np.median(randint_arr)

6.0

In [90]:
np.percentile(randint_arr, 100)

1000.0

In [91]:
randint_arr[randint_arr <= np.percentile(randint_arr, 99)]

array([5, 1, 5, 6, 6, 9, 3, 7, 8, 1, 5, 3, 8, 6, 7, 8, 2, 4, 3, 9])

In [92]:
randint_arr2 = np.array([*np.random.randint(0, 10, size=20), 1000, 1000, 1000, 1000])
randint_arr2

array([   1,    3,    7,    6,    8,    4,    3,    5,    4,    8,    5,
          4,    0,    4,    6,    6,    2,    4,    6,    1, 1000, 1000,
       1000, 1000])

In [93]:
randint_arr2[randint_arr2 <= np.percentile(randint_arr2, 99)]

array([   1,    3,    7,    6,    8,    4,    3,    5,    4,    8,    5,
          4,    0,    4,    6,    6,    2,    4,    6,    1, 1000, 1000,
       1000, 1000])

In [99]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
np.save('array_file.npy', x)

In [101]:
y = np.load('array_file.npy')
y # 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Обов'язково при завантаженні вказувати розширення npy. Завантажує в бінарних даних