## Lesson 7

In [6]:
import numpy as np

In [7]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [9]:
arr * 2 / 3

array([0.66666667, 1.33333333, 2.        , 2.66666667, 3.33333333])

In [11]:
arr_2d = np.array([[1, 2, 3, 4, 5], [2, 4, 5, 3, 1]])
arr_2d

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 3, 1]])

In [12]:
(arr_2d + 6) * 5 / 20

array([[1.75, 2.  , 2.25, 2.5 , 2.75],
       [2.  , 2.5 , 2.75, 2.25, 1.75]])

In [13]:
arr_md = np.array([[[i + j + k for k in range(5)] for j in range(4)] for i in range(3)])
arr_md

array([[[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]],

       [[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7],
        [4, 5, 6, 7, 8]],

       [[2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7],
        [4, 5, 6, 7, 8],
        [5, 6, 7, 8, 9]]])

In [15]:
arr_md /3

array([[[0.        , 0.33333333, 0.66666667, 1.        , 1.33333333],
        [0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667],
        [0.66666667, 1.        , 1.33333333, 1.66666667, 2.        ],
        [1.        , 1.33333333, 1.66666667, 2.        , 2.33333333]],

       [[0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667],
        [0.66666667, 1.        , 1.33333333, 1.66666667, 2.        ],
        [1.        , 1.33333333, 1.66666667, 2.        , 2.33333333],
        [1.33333333, 1.66666667, 2.        , 2.33333333, 2.66666667]],

       [[0.66666667, 1.        , 1.33333333, 1.66666667, 2.        ],
        [1.        , 1.33333333, 1.66666667, 2.        , 2.33333333],
        [1.33333333, 1.66666667, 2.        , 2.33333333, 2.66666667],
        [1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ]]])

In [16]:
arr_md.ndim # количество масивов

3

In [17]:
arr_md.shape # кількість елементів в масиві

(3, 4, 5)

In [18]:
arr_md.size #3*4*5

60

In [19]:
arr_md.dtype

dtype('int32')

In [23]:
np.zeros((5, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
np.ones((5, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
np.arange(0, 15, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [28]:
np.arange(15, 0, -2)

array([15, 13, 11,  9,  7,  5,  3,  1])

In [30]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])